import Lax16.TeachingMaps
import Lax16.AnchorLabels
import Lax16.PlanarGraphs
import Lax16.BatchFramework
import Lax16.BatchReassignment
import Lax16.SmallDegreeBatch
import Lax16.DominatorDefinitions
import Lax16.OuterplanarBlockAssignment
import Lax16.OuterplanarBound
import Lax16.OuterplanarSharpness
import Lax16.OuterplanarLayer
import Lax16.DominatorCount
import Lax16.PlanarVertexBatch
import Lax16.PlanarBound
import Lax16.PlanarSharpness
